export const ToyItems = [
  [
    {
      index: 'Book 1',
      name: '해리포터 스튜디오 가이드북',
      colors: ['#AC8035', '#F7F8F8', '#334642'],
      member: '개인',
      period: '2016년 8월',
      objective: '해리포터 스튜디오를 안내하는 ',
      boldObj: '투어 가이드북 제작',
      program: 'Photoshop, indesign',
    }
  ],
  [
    {
      index: 'Book 1',
      name: '해리포터 스튜디오 가이드북',
      colors: ['#AC8035', '#F7F8F8', '#334642'],
      member: '개인',
      period: '2016년 8월',
      objective: '해리포터 스튜디오를 안내하는 ',
      boldObj: '투어 가이드북 제작',
      program: 'Photoshop, indesign',
    },
    {
      index: 'Book 2',
      name: 'dumbo(덤보)',
      colors: ['#ECBEC4', '#F7F8F8', '#BDBAC5'],
      member: '개인',
      period: '2017년 1월',
      objective: '직접 촬영한 사진으로 여행잡지 ',
      boldObj: '북커버 제작',
      program: 'Photoshop, indesign',
    },
    {
      index: 'Book 3',
      name: '푸른 안개',
      colors: ['#000000', '#C7D4E5', '#FFFFFF'],
      member: '개인',
      period: '2017년 3월',
      objective: '스토리보드 구상 후 ',
      boldObj: '소설책 커버 제작',
      program: 'Photoshop, indesign',
    },
  ],
  [
    {
      index: 'Poster 1',
      name: '아멜리에',
      colors: [
        ['#BB2F20', '#DD7D04', '#E6E2D7'],
        ['#BB2F20', '#DD7D04', '#2B3F0A'],
      ],
      member: '개인',
      period: '2016년 8월',
      objective: '',
      boldObj: '영화 포스터 제작',
      program: 'Photoshop, illustrator',
    },
    {
      index: 'Poster 2',
      name: '신비한 동물사전',
      colors: [
        ['#3A60B5', '#B5EEFF', '#59268F'],
        ['#CCD0EB', '#FFC5C9', '#FDFCFC'],
        ['#68C246', '#DEFFCA', '#5A4632'],
      ],
      member: '개인',
      period: '2019년 8월',
      objective: '',
      boldObj: '영화 포스터 제작',
      program: 'Photoshop, illustrator',
    },
    {
      index: 'Poster 3',
      name: '삿포로 벚꽃 축제',
      colors: ['#B1EBDC', '#D75D72', '#A9CEE9'],
      member: '개인',
      period: '2016년 11월',
      objective: '',
      boldObj: '축제 포스터 제작',
      program: 'Photoshop, illustrator',
    },
  ],
];
